name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_email: ${{secrets.HEROKU_EMAIL}}
            heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
            branch: main
            appdir: acme-coffee-server
          env:
            HD_DB_NAME: ${{secrets.DB_NAME}}
            HD_DB_USER: ${{secrets.DB_USER}}
            HD_DB_HOST: ${{secrets.DB_HOST}}
            HD_DB_PASSWORD: ${{secrets.DB_PASSWORD}}
